---
title: "Data manipulation"
author: "Jingqi Song"
date: "September 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

# Manipulation

select:for columns
fill out:for rows

## Import FAS csv files

import my first csv to use as examples

```{r}
litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```

## select variables

```{r}
select(litters_data,litter_number,gd0_weight,pups_survive)

```

...by specifying a range;

```{r}
select(litters_data,gd_of_birth:pups_survive)
select(litters_data,group,gd_of_birth:pups_survive)
```

...by saying what you want to remove;

```{r}
select(litters_data,-litter_number)
```

...rename;

```{r}
select(litters_data,group,litter_number,gest_day_0_weight = gd0_weight)
rename(litters_data,gest_day_0_weight = gd0_weight)
```

...use select helpers

```{r}
select(litters_data,group,starts_with('gd'))
select(litters_data,starts_with('gd'))

select(litters_data,litter_number,everything())
```

learning assessment: pups dataset

```{r}
select(pups_data, litter_number, sex, pd_ears)
```

## filter observations

true or false? if it is ... i'm gonna to keep this thing
==: whether the 2 things are the same

```{r}
filter(litters_data,gd0_weight<25)
filter(litters_data,pups_born_alive == 8)

filter(litters_data,is.na(gd0_weight))
filter(litters_data,!is.na(gd0_weight))

filter(litters_data, group == 'low8' | group == 'low7')
filter(litters_data, group %in% c('low8', 'low7'))

filter(litters_data, pups_born_alive %in% 4:6)

filter(litters_data, pups_born_alive %in% 4:7, !is.na(gd0_weight))
```




