---
title: "data_tidy"
author: "Jingqi Song"
date: "September 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```
## gather
pulse data

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data

pulse_tidy = gather(pulse_data, key = visit, value = bdi, bdi_score_bl:bdi_score_12m)
str(pulse_data)
```

illustrate 'separate'

```{r}
pulse_tidy %>%
  separate (pulse_tidy_data, visit, into = c("bdi_str", "score_str", "visit"), sep = "_" %>%
  select(-bdi_str,-score_str) %>%
    mutate(visit = replace(visit,visit == 'bl','00m')) 
                  )
```

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  gather(key = visit, value = bdi, bdi_score_bl:bdi_score_12m) %>%
  separate(visit, into = c("remove_1", "remove_2", "visit"), sep = "_") %>%
  select(id, visit, everything(), -starts_with("remove")) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"),
         visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)
```

## Revisit litters_data

```{r}
read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>%
  count(group) 
```

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  mutate(dose = tolower(dose),
         wt_gain = gd18_weight - gd0_weight) %>%
  arrange(litter_number)

litters_data
```

learning assessment
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>%
  select(litter_number,ends_with('weight')) %>%
  gather(key = 'gest_day', value = gd0_weight:gd18_weight) %>%
  arrange (litter_number)
 
litters_data
```

analysis results
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
```

make it readable

```{r}
analysis_result %>%
  spread(key=time,value=mean)

```

## Binding rows
Read in LotR data

```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

Create final lotr data
```{r}
bind_rows(fellowship_ring,two_towers,return_king)%>%
  janitor::clean_names()%>%
  gather(key = sex, value = words, female:male) %>%
  mutate(race = tolower(race)) 
```

## join data

```{r}
pup_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group))
```

create joined data

```{r}
fas_data = left_join(pup_data,litter_data,by = 'litter_number')
```

joined command in a pipeline is not recommended!!!!



